---
title: "Bucks"
output: html_document
---

```{r}
library(tidyverse)
read.csv("chances.csv") -> Chances
```


```{r}
#Points allowed per possession if intentional foul occurs
Chances %>%
  filter(period == 4, outcome == "FOU_B") %>%
  count(test = sum(ptsScored_team) / n())
#Winning percentage if defensive team intentionally fouls at any point under 24 seconds
Chances %>%
  group_by(gid_nba, team_nba_def) %>%
  filter(period == 4, any(outcome == "FOU_B")) %>%
  ungroup() %>%
  mutate(WIN = ifelse(team_nba_winner == team_nba_def, 1, 0)) %>%
  distinct(gid_nba, team_nba_def, .keep_all = TRUE) %>%
  count(test = sum(WIN) / n())

#Points allowed per possession if intentional foul does not occur
Chances %>%
  filter(period == 4, outcome != "FOU_B", outcome != "FOU_N", outcome != "TMO") %>%
  count(test = sum(ptsScored_team) / n())
#Winning percentage if defensive team does not intentionally foul at any point under 24 seconds
Chances %>%
  group_by(gid_nba, team_nba_def) %>%
  filter(period == 4, any(outcome != "FOU_B")) %>%
  ungroup() %>%
  mutate(WIN = ifelse(team_nba_winner == team_nba_def, 1, 0)) %>%
  distinct(gid_nba, team_nba_def, .keep_all = TRUE) %>%
  count(test = sum(WIN) / n())
```



```{r}
Chances %>%
  filter(period == 4, outcome == "FOU_B") %>%
  mutate(timeleft_bin = cut(gameClock_end, breaks = c(0, 5, 10, 15, 20), include.lowest = TRUE)) %>%
  mutate(WIN = ifelse(team_nba_winner == team_nba_def, 1, 0)) %>%
  group_by(timeleft_bin) %>%
  summarise(WP = sum(WIN) / n(), IntentionalFoul = "Foul") -> ChancesFoul

Chances %>%
  filter(period == 4, outcome != "FOU_B", outcome != "TIM", outcome != "FOU_N") %>%
  mutate(timeleft_bin = cut(gameClock_end, breaks = c(0, 5, 10, 15, 20), include.lowest = TRUE)) %>%
  mutate(WIN = ifelse(team_nba_winner == team_nba_def, 1, 0)) %>%
  group_by(timeleft_bin) %>%
  summarise(WP = sum(WIN) / n(),  IntentionalFoul = "No Foul") %>%
  rbind(ChancesFoul)-> ChancesFoul

ChancesFoul[,'WP']=round(ChancesFoul[,'WP'],3)

library(ggplot2)
ggplot(ChancesFoul, aes(x = IntentionalFoul, y = WP)) +
  geom_bar(stat = "identity", alpha = 0.7, fill = "#00471B") +
  facet_grid(. ~timeleft_bin)  +
  ylim(0,1) +
  geom_text(aes(label = WP), vjust = 1.5, color = "#EEE1C6", size = 4) +
  labs(x = "\n Foul vs No Foul", y = "Win Percentage\n", title = "\n Winning Pecentage By Time Remaining \n") +
  theme(plot.title = element_text(face = "bold", hjust = 0.5), 
        axis.title.x = element_text(colour="black", size = 12),
        axis.title.y = element_text(colour="black", size = 12),
        legend.title = element_text(face="bold", size = 10),
        strip.background = element_rect(fill="#EEE1C6", colour="black", size=1),
        strip.text = element_text(face="bold", colour = "#00471B", size=rel(1.2))) -> WinByTime

ggsave("WinByTime.png", plot = WinByTime, width = 6, height = 4)
```

